#############################################################################
# Makefile for building: bin/stildcpp
# Generated by qmake (2.01a) (Qt 4.3.1) on: ?? ???. 4 16:10:23 2007
# Project:  stildcpp.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile stildcpp.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Ibuild -Ibuild
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib64/qt4 -lQtGui -L/usr/lib64 -L/usr/lib64/qt4 -L/usr/lib -lpng -lSM -lICE -lXrender -lXrandr -lXfixes -lXcursor -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -lrt -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/mainwindowimpl.cpp \
		src/main.cpp \
		src/frmAbout.cpp \
		src/mdi_c.cpp \
		src/preferencesdialog.cpp \
		src/config.cpp \
		src/quickconnectdlg.cpp build/moc_mainwindowimpl.cpp \
		build/moc_mdi_c.cpp \
		build/moc_preferencesdialog.cpp \
		build/moc_quickconnectdlg.cpp \
		qrc_stildcpp.cpp
OBJECTS       = build/mainwindowimpl.o \
		build/main.o \
		build/frmAbout.o \
		build/mdi_c.o \
		build/preferencesdialog.o \
		build/config.o \
		build/quickconnectdlg.o \
		build/moc_mainwindowimpl.o \
		build/moc_mdi_c.o \
		build/moc_preferencesdialog.o \
		build/moc_quickconnectdlg.o \
		build/qrc_stildcpp.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		stildcpp.pro
QMAKE_TARGET  = stildcpp
DESTDIR       = bin/
TARGET        = bin/stildcpp

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_mainwindow.h build/ui_about.h build/ui_preferencesdialog.h build/ui_PMWindow.h build/ui_HUBWindow.h build/ui_search.h build/ui_favhublist.h build/ui_quickconnect.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: stildcpp.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/libQtGui.prl \
		/usr/lib64/qt4/libQtCore.prl
	$(QMAKE) -unix -o Makefile stildcpp.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/libQtGui.prl:
/usr/lib64/qt4/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile stildcpp.pro

dist: 
	@$(CHK_DIR_EXISTS) build/stildcpp1.0.0 || $(MKDIR) build/stildcpp1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/stildcpp1.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.h src/frmAbout.h src/mdi_c.h src/preferencesdialog.h src/config.h src/quickconnectdlg.h build/stildcpp1.0.0/ && $(COPY_FILE) --parents src/stildcpp.qrc build/stildcpp1.0.0/ && $(COPY_FILE) --parents src/mainwindowimpl.cpp src/main.cpp src/frmAbout.cpp src/mdi_c.cpp src/preferencesdialog.cpp src/config.cpp src/quickconnectdlg.cpp build/stildcpp1.0.0/ && $(COPY_FILE) --parents ui/mainwindow.ui ui/about.ui ui/preferencesdialog.ui ui/PMWindow.ui ui/HUBWindow.ui ui/search.ui ui/favhublist.ui ui/quickconnect.ui build/stildcpp1.0.0/ && (cd `dirname build/stildcpp1.0.0` && $(TAR) stildcpp1.0.0.tar stildcpp1.0.0 && $(COMPRESS) stildcpp1.0.0.tar) && $(MOVE) `dirname build/stildcpp1.0.0`/stildcpp1.0.0.tar.gz . && $(DEL_FILE) -r build/stildcpp1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_mainwindowimpl.cpp build/moc_mdi_c.cpp build/moc_preferencesdialog.cpp build/moc_quickconnectdlg.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_mainwindowimpl.cpp build/moc_mdi_c.cpp build/moc_preferencesdialog.cpp build/moc_quickconnectdlg.cpp
build/moc_mainwindowimpl.cpp: build/ui_mainwindow.h \
		src/config.h \
		src/frmAbout.h \
		build/ui_about.h \
		src/preferencesdialog.h \
		build/ui_preferencesdialog.h \
		src/mdi_c.h \
		build/ui_PMWindow.h \
		build/ui_HUBWindow.h \
		build/ui_search.h \
		build/ui_favhublist.h \
		src/quickconnectdlg.h \
		build/ui_quickconnect.h \
		src/mainwindowimpl.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/mainwindowimpl.h -o build/moc_mainwindowimpl.cpp

build/moc_mdi_c.cpp: build/ui_PMWindow.h \
		build/ui_HUBWindow.h \
		build/ui_search.h \
		build/ui_favhublist.h \
		src/mdi_c.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/mdi_c.h -o build/moc_mdi_c.cpp

build/moc_preferencesdialog.cpp: build/ui_preferencesdialog.h \
		src/preferencesdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/preferencesdialog.h -o build/moc_preferencesdialog.cpp

build/moc_quickconnectdlg.cpp: build/ui_quickconnect.h \
		src/quickconnectdlg.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/quickconnectdlg.h -o build/moc_quickconnectdlg.cpp

compiler_rcc_make_all: qrc_stildcpp.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_stildcpp.cpp
qrc_stildcpp.cpp: src/stildcpp.qrc \
		src/images/splash.png \
		src/images/icon_error.png \
		src/images/icon.png \
		src/images/QuickCon.png \
		src/images/icon_mail.png
	/usr/bin/rcc -name stildcpp src/stildcpp.qrc -o qrc_stildcpp.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_mainwindow.h build/ui_about.h build/ui_preferencesdialog.h build/ui_PMWindow.h build/ui_HUBWindow.h build/ui_search.h build/ui_favhublist.h build/ui_quickconnect.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_mainwindow.h build/ui_about.h build/ui_preferencesdialog.h build/ui_PMWindow.h build/ui_HUBWindow.h build/ui_search.h build/ui_favhublist.h build/ui_quickconnect.h
build/ui_mainwindow.h: ui/mainwindow.ui
	/usr/bin/uic ui/mainwindow.ui -o build/ui_mainwindow.h

build/ui_about.h: ui/about.ui
	/usr/bin/uic ui/about.ui -o build/ui_about.h

build/ui_preferencesdialog.h: ui/preferencesdialog.ui
	/usr/bin/uic ui/preferencesdialog.ui -o build/ui_preferencesdialog.h

build/ui_PMWindow.h: ui/PMWindow.ui
	/usr/bin/uic ui/PMWindow.ui -o build/ui_PMWindow.h

build/ui_HUBWindow.h: ui/HUBWindow.ui
	/usr/bin/uic ui/HUBWindow.ui -o build/ui_HUBWindow.h

build/ui_search.h: ui/search.ui
	/usr/bin/uic ui/search.ui -o build/ui_search.h

build/ui_favhublist.h: ui/favhublist.ui
	/usr/bin/uic ui/favhublist.ui -o build/ui_favhublist.h

build/ui_quickconnect.h: ui/quickconnect.ui
	/usr/bin/uic ui/quickconnect.ui -o build/ui_quickconnect.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/mainwindowimpl.o: src/mainwindowimpl.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/config.h \
		src/frmAbout.h \
		build/ui_about.h \
		src/preferencesdialog.h \
		build/ui_preferencesdialog.h \
		src/mdi_c.h \
		build/ui_PMWindow.h \
		build/ui_HUBWindow.h \
		build/ui_search.h \
		build/ui_favhublist.h \
		src/quickconnectdlg.h \
		build/ui_quickconnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainwindowimpl.o src/mainwindowimpl.cpp

build/main.o: src/main.cpp src/mainwindowimpl.h \
		build/ui_mainwindow.h \
		src/config.h \
		src/frmAbout.h \
		build/ui_about.h \
		src/preferencesdialog.h \
		build/ui_preferencesdialog.h \
		src/mdi_c.h \
		build/ui_PMWindow.h \
		build/ui_HUBWindow.h \
		build/ui_search.h \
		build/ui_favhublist.h \
		src/quickconnectdlg.h \
		build/ui_quickconnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/frmAbout.o: src/frmAbout.cpp src/frmAbout.h \
		build/ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/frmAbout.o src/frmAbout.cpp

build/mdi_c.o: src/mdi_c.cpp src/mdi_c.h \
		build/ui_PMWindow.h \
		build/ui_HUBWindow.h \
		build/ui_search.h \
		build/ui_favhublist.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mdi_c.o src/mdi_c.cpp

build/preferencesdialog.o: src/preferencesdialog.cpp src/config.h \
		src/preferencesdialog.h \
		build/ui_preferencesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/preferencesdialog.o src/preferencesdialog.cpp

build/config.o: src/config.cpp src/config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/config.o src/config.cpp

build/quickconnectdlg.o: src/quickconnectdlg.cpp src/quickconnectdlg.h \
		build/ui_quickconnect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/quickconnectdlg.o src/quickconnectdlg.cpp

build/moc_mainwindowimpl.o: build/moc_mainwindowimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainwindowimpl.o build/moc_mainwindowimpl.cpp

build/moc_mdi_c.o: build/moc_mdi_c.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mdi_c.o build/moc_mdi_c.cpp

build/moc_preferencesdialog.o: build/moc_preferencesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_preferencesdialog.o build/moc_preferencesdialog.cpp

build/moc_quickconnectdlg.o: build/moc_quickconnectdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_quickconnectdlg.o build/moc_quickconnectdlg.cpp

build/qrc_stildcpp.o: qrc_stildcpp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_stildcpp.o qrc_stildcpp.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

